### PR TITLE
Add bless to split CSS for IE9

### PR DESCRIPTION
**Pull request by jessedvrs**
All CSS beyond the 4095th selector is being ignored in IE9. Therefore, there is BlessCSS.
Couldn't get source maps to work again though. Maybe you could take a look at that :)

### CODE REVIEW

**Comment by sebakerckhof** [comment]
I thought Meteor already did this for me: https://github.com/meteor/meteor/issues/1876

**Comment by sebakerckhof** [comment]
Basically this call to the meteor minifier: https://github.com/sebakerckhof/meteor-minifiers-autoprefix/blob/master/plugin/minify-css.js#L69

Should already give me files capped at 4095 selectors. Is this not the case for you?

Related: https://github.com/meteor/meteor/blob/devel/packages/minifier-css/minification.js
from this commit: https://github.com/meteor/meteor/commit/7c729b90a4faca564972880d05b787f7a9e604bf

**Comment by jessedvrs** [comment]
You are right, I was confused since that isn't the case for non-production builds, which is really confusing for debugging on IE9.

**Comment by sebakerckhof** [comment]
Then IMO it would be better to add this to Meteor, so we don't do this work in 2 places.
I think they're going to be reluctant since it would increase refresh times even more, but maybe if it's behind a flag?

**Comment by jessedvrs** [comment]
Agree it's a Meteor thing, not yours. Thanks and I'll keep you posted if I find something.

**Pull request closed without merging**
